version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_DEV=development
      - MONGO_USER=vaibhav
      - MONGO_PASSWORD=mypassword
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vaibhav
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

