version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_DEV=development
    command: npm run dev
    # overwrite hone wala hain vaise bhi
